utf-8 is changed to ISO-8859-1
Decode to utf-8 couse an error such that:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position
106165: invalid start byte